ImageService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_app.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'image_app'
urlpatterns = [
    path('',views.index, name="index"),
    path('users_detail/<int:pk>/', views.users_detail, name='users_detail'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='image_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

image_app/models.py
from django.db import models
from django.contrib.auth.models import User

CHOICE = (
	('', '変換方法を選んでください'),
    ('グレースケール', 'グレースケール'),
    ('モザイク', 'モザイク'),
    ('フェイスモザイク', 'フェイスモザイク'),
    ('モザイクgif', 'モザイクgif'),
)
class Document(models.Model):
	description = models.CharField('画像変換方法', max_length=255, choices=CHOICE)
	photo = models.ImageField('画像選択', upload_to='documents/')
	uploaded_at = models.DateTimeField(auto_now_add=True)
	output = models.ImageField(default = 'output/output.jpg')
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.description

image_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
	class Meta:
		model = Document
		fields = ['description', 'photo']

# class MosaicDocumentForm(forms.ModelForm):
# 	class Meta:
# 		model = Document
# 		fields = ['description', 'photo']

image_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DocumentForm
from .models import Document
import cv2
import numpy as np
from django.conf import settings
from PIL import Image
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

@login_required
def index(request):
	return render(request, 'image_app/index.html')
	
	# document_list = Document.objects.all().order_by('-id')

	# if request.method == 'POST':
	# 	form = DocumentForm(request.POST, request.FILES)
	# 	if form.is_valid():
	# 		photo_data = form.save()
	# 		max_id = Document.objects.latest('id').id
	# 		max_id_str = str(max_id)
	# 		obj = Document.objects.get(id = max_id)
	# 		input_path = settings.BASE_DIR + obj.photo.url
	# 		output_path = settings.BASE_DIR + "/media/output/" + max_id_str + ".jpg"
	# 		output_path_gif = settings.BASE_DIR + "/media/output/" + max_id_str + ".gif"
	# 		img = cv2.imread(input_path)
	# 		if obj.description == "グレースケール":
	# 			img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
	# 			cv2.imwrite(output_path, img_gray)
	# 			output_path = output_path.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
	# 			photo_data.output = output_path
	# 			photo_data.save()
	# 			messages.success(request, "グレースケールに変換しました！")
	# 		elif obj.description == "モザイク":
	# 			small = cv2.resize(img, None, fx=0.1, fy=0.1, interpolation=cv2.INTER_NEAREST)
	# 			big = cv2.resize(small, img.shape[:2][::-1], interpolation=cv2.INTER_NEAREST)
	# 			cv2.imwrite(output_path, big)
	# 			output_path = output_path.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
	# 			photo_data.output = output_path
	# 			photo_data.save()
	# 			messages.success(request, "モザイクをかけました！")
	# 		elif obj.description == "フェイスモザイク":
	# 			face_cascade_path = settings.BASE_DIR + "/data/haarcascade_frontalface_default.xml"
	# 			face_cascade = cv2.CascadeClassifier(face_cascade_path) # カスケード分類器のファイルの中身を読み込む
	# 			src_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #RGBからグレースケールに変換
	# 			rects = face_cascade.detectMultiScale(src_gray, 1.1, 3,0, (20,20))
	# 			if len(rects) > 0:
	# 				for rect in rects:
	# 					x, y, w, h = rect
	# 					face = img[y:y+h, x:x+w]
	# 					dst = cv2.GaussianBlur(face, (25, 25), 0)
	# 					img[y:y+h, x:x+w] = dst
	# 			else:
	# 				pass
	# 			cv2.imwrite(output_path, img)
	# 			output_path = output_path.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
	# 			photo_data.output = output_path
	# 			photo_data.save()
	# 			messages.success(request, "顔にモザイクをかけました！")
	# 		elif obj.description == "モザイクgif":
	# 			src= cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
	# 			imgs = [Image.fromarray(mosaic(src, 1 / i)) for i in range(1, 25)]
	# 			imgs += imgs[-2::-1] + [Image.fromarray(src)] * 5
	# 			imgs[0].save(output_path_gif, commit=False, save_all=True, append_images=imgs[1:], optimize=False, duration=50, loop=0)
	# 			output_path_gif = output_path_gif.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
	# 			photo_data.output = output_path_gif
	# 			photo_data.save()
	# 			messages.success(request, "モザイクgifに変換しました！") 
	# 		else:
	# 			pass

	# 		return redirect('image_app:index')

	# else:
	# 	form = DocumentForm()

	# return render(request, 'image_app/index.html', {'form': form, 'document_list': document_list, })

@login_required
def users_detail(request, pk):
	login_user = request.user.pk
	user = get_object_or_404(User, pk=pk)
	print(user)
	document_list = user.document_set.all().order_by('-id')
	print(document_list)

	if request.method == 'POST':
		form = DocumentForm(request.POST, request.FILES)
		if form.is_valid():
			photo_data = form.save(commit=False)
			photo_data.user = request.user
			photo_data = form.save()
			max_id = Document.objects.latest('id').id
			max_id_str = str(max_id)
			obj = Document.objects.get(id = max_id)
			input_path = settings.BASE_DIR + obj.photo.url
			output_path = settings.BASE_DIR + "/media/output/" + max_id_str + ".jpg"
			output_path_gif = settings.BASE_DIR + "/media/output/" + max_id_str + ".gif"
			img = cv2.imread(input_path)
			if obj.description == "グレースケール":
				img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
				cv2.imwrite(output_path, img_gray)
				output_path = output_path.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
				photo_data.output = output_path
				photo_data.save()
				messages.success(request, "グレースケールに変換しました！")
			elif obj.description == "モザイク":
				small = cv2.resize(img, None, fx=0.1, fy=0.1, interpolation=cv2.INTER_NEAREST)
				big = cv2.resize(small, img.shape[:2][::-1], interpolation=cv2.INTER_NEAREST)
				cv2.imwrite(output_path, big)
				output_path = output_path.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
				photo_data.output = output_path
				photo_data.save()
				messages.success(request, "モザイクをかけました！")
			elif obj.description == "フェイスモザイク":
				face_cascade_path = settings.BASE_DIR + "/data/haarcascade_frontalface_default.xml"
				face_cascade = cv2.CascadeClassifier(face_cascade_path) # カスケード分類器のファイルの中身を読み込む
				src_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #RGBからグレースケールに変換
				rects = face_cascade.detectMultiScale(src_gray, 1.1, 3,0, (20,20))
				if len(rects) > 0:
					for rect in rects:
						x, y, w, h = rect
						face = img[y:y+h, x:x+w]
						dst = cv2.GaussianBlur(face, (25, 25), 0)
						img[y:y+h, x:x+w] = dst
				else:
					pass
				cv2.imwrite(output_path, img)
				output_path = output_path.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
				photo_data.output = output_path
				photo_data.save()
				messages.success(request, "顔にモザイクをかけました！")
			elif obj.description == "モザイクgif":
				src= cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
				imgs = [Image.fromarray(mosaic(src, 1 / i)) for i in range(1, 25)]
				imgs += imgs[-2::-1] + [Image.fromarray(src)] * 5
				imgs[0].save(output_path_gif, commit=False, save_all=True, append_images=imgs[1:], optimize=False, duration=50, loop=0)
				output_path_gif = output_path_gif.replace("/Users/suehiro/1pro/Django/image_app/ImageService/media", "")
				photo_data.output = output_path_gif
				photo_data.save()
				messages.success(request, "モザイクgifに変換しました！") 
			else:
				pass

			return redirect('image_app:users_detail', pk=request.user.pk)

	else:
		form = DocumentForm()

	return render(request, 'image_app/users_detail.html', {'form': form, 'document_list': document_list, 'user': user})

def mosaic(src, ratio=0.1):
    small = cv2.resize(src, None, fx=ratio, fy=ratio, interpolation=cv2.INTER_NEAREST)
    return cv2.resize(small, src.shape[:2][::-1], interpolation=cv2.INTER_NEAREST)


@require_POST
def delete(request, pk):
	delete_data = get_object_or_404(Document, pk=pk)
	delete_data.delete()
	messages.success(request, "データを削除")
	return redirect('image_app:users_detail', request.user.id)

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			input_username =form.cleaned_data['username']
			input_password = form.cleaned_data['password1']
			#usernameとpasswordを引数に取り、その組み合わせで認証に成功すればUserオブジェクトを返す。認証できなければNoneを返す。
			new_user = authenticate(username=input_username, password=input_password)
			if new_user is not None:
				# リクエスト情報とUserオブジェクトを引数に取り、そのユーザーを未ログイン状態からログイン状態にする。
				# login(request, new_user)
				# return redirect('image_app:login', pk=new_user.pk)
				messages.success(request, "ユーザー登録が完了しました！") 
				return redirect('image_app:login')
	else:
		form = UserCreationForm()
	return render(request, 'image_app/signup.html', {'form': form})

templates/image_app/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css%}
{% load widget_tweaks %}
{% block content %}
{% load static %}

<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="card-body">
				<h3 class="text-center font-weight-bold mb-4" style="color: #666666;">Image Transformは画像を白黒にしたり、<br>モザイク加工したりするためのアプリです。</h3>
				{% if user.is_authenticated %}
		    	<h6 class="text-center font-weight-bold mb-4" style="color: #666666;">{{ user.username }}さん、こんにちは。</h6>
		    	<div class="row justify-content-center">
		    		<a class="mr-4 btn btn-lg btn-primary" role="button" href="{% url 'image_app:users_detail' user.id %}">あなたページへ</a>
			    </div>
			    {% else %}
			    <h3 class="text-center font-weight-bold mb-4" style="color: #666666;">こんにちは。ゲストさん</h3>
			    <div class="row justify-content-center">
			    	<a class="mr-4 btn btn-lg btn-primary" role="button" href="{% url 'image_app:login' %}" >ログイン</a>
			    	<a class="btn btn-lg btn-primary" role="button" href="{% url 'image_app:signup' %}">ユーザー登録</a>
			    </div>
				{% endif %}
			</div>
		</div>
	</div>
</div>		
{% endblock %}

templates/image_app/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load widget_tweaks %}

{% block content %}
<div class="row justify-content-center">
	<div class="col-lg-8 col-md-10 col-sn-12">
		<div class="card-body">
		    <form class="form-signin" method="post">{% csrf_token %}
		    {% if form.errors %}
		        <p>ユーザー名かパスワードが間違っています。もう一度入力してください。</p>
		    {% endif %}
		    	<h2>ログイン</h2>
				{% bootstrap_form form %}
			    <input type="submit" class="btn btn-primary btn-block" value="ログイン">
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/image_app/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load widget_tweaks %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sn-12">
        <div class="card-body">
            <h2>ユーザー登録</h2>

            <form method="post" action="{% url 'image_app:signup' %}">{% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary btn-block" value="登録する">
            </form>
            <br>
            <p class="card-footer text-muted text-center"><a href="{% url 'image_app:login' %}">ログインはこちら</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/image_app/users_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css%}
{% load widget_tweaks %}
{% block content %}
{% load static %}

<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">

			{# --- django_widgets_tweaks version --- #}
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="input-group mb-2">
				    <label class="input-group-btn">
				        <span class="btn btn-primary">
				        	{% render_field form.photo class="form-control" type="file" style="display:none" %}Choose File
				        </span>
				    </label>
				    <input type="text" class="form-control" readonly="">
				</div>
				<div class="form-group row">
				    <label for="{{ form.description.id_for_label }}"></label>
				    <div class="col-sm-12">
				      {{ form.description|add_class:'form-control' }}
				    </div>
				</div>

				<!-- <div class="form-group row">
				    <label for="{{ form.description.id_for_label }}" class="col-sm-3 col-form-label h2">変換方法</label>
				    <div class="col-sm-9">
				      {{ form.description|add_class:'form-control' }}
				      {% for error in form.description.errors %}
				        <span class="help-block">{{ error }}</span>
				      {% endfor %}
				    </div>
				</div> -->
				<!-- <div class="form-group row">
				    <label for="{{ form.photo.id_for_label }}" class="col-sm-3 col-form-label">画像選択</label>
				    <div class="col-sm-9">
				      {{ form.photo|add_class:'form-control' }}
				      {% render_field form.photo class="form-control-file" type="file" %}
				      {% for error in form.photo.errors %}
				        <span class="help-block">{{ error }}</span>
				      {% endfor %}
				    </div>
				</div> -->
				<button type="submit" class="btn btn-primary btn-block" role="button">Upload</button>
			</form>

			
			<script type="text/javascript">
				// get image name
				$(document).on('change', ':file', function() {
				    var input = $(this),
				    numFiles = input.get(0).files ? input.get(0).files.length : 1,
				    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
				    input.parent().parent().next(':text').val(label);
				});


				//datatables
				jQuery(function($){
						$.extend( $.fn.dataTable.defaults, { 
				        language: {
				            url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
				        } 
				    }); 

				        $("#data-table").DataTable({
				        	"columnDefs": [{ className: "dt-nowrap", "targets": [ '_all' ]}],
				        	"order": [[ 0, "desc" ]],
				        });
				    });

			</script>

			</div>
		</div>
	</div>
</div>

<style type="text/css" media="screen">

</style>

<div class="container">
	<div id="table-members">
		<div class="d-xl-inline col-lg-12 col-md-12 col-sm-12">
			<h5 class="text-center font-weight-bold textcolor" style="color: #666666;">変換データ</h5>
			<div class="table-responsive">
				<div class="table-1">
					<table border="1" id="data-table" class=" table-sm table-bordered table-striped">
						<thead>
							<tr class="bg-dark text-white">
								<th>ID</th>
								<th>作成日</th>
								<th>元画像</th>
								<th>画像変換方法</th>
								<th>変換画像</th>
								<th>削除</th>
							</tr>
						</thead>
						<tbody>	
						{% for document_list in document_list %}
							<tr>
								{% if request.user == document_list.user %}
								<td>{{ document_list.id }}</td>
								<td>{{ document_list.uploaded_at }}</td>
								<td><a class="btn btn-primary" href="{{MEDIA_URL}}{{ document_list.photo.url }}">元画像</a></td>
								<td>{{ document_list.description }}</td>
								<td><a class="btn btn-primary" href="{{MEDIA_URL}}/media{{ document_list.output }}">画像</a></td>
								<td>
									<form method="post" action="{% url 'image_app:delete' document_list.id %}">{% csrf_token %}
								    <button class="btn-sm btn-primary" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
									</form>
								</td>
								{% endif %}
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}