ImageService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_app.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'image_app'
urlpatterns = [
    path('',views.index, name="index"),
    path('users_detail/<int:pk>/', views.users_detail, name='users_detail'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='image_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

templates/base.html
<!DOCTYPE html>
{% load bootstrap4%}
{% bootstrap_css%}
{% bootstrap_javascript jquery='True'%} 
{% load static %}
<html lang="ja">

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!--TITLE-->
		<title>{% block title %}Image Transform{% endblock %}</title>

		{# --- START CSS --- #}
		<!--LOAD CSS-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<!--BOOTSTRAP-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<!-- JQUERY-UI.CSS -->
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<!--DATATABLES-->
		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
		{# --- END CSS --- #}

	</head>

	<body style="padding-top:4.5rem;"><!--NAVBAR固定に必要-->

		<main>
			<!--START NAVBAR-->
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

				<!--START BRAND TITLE-->
				<div class = "font-weight-bold">
					<a class="navbar-brand text-white" href="{% url 'image_app:index' %}">Image Transform</a>
				</div>
				<!--END BRAND TITLE-->

				<!--START TOGGLE-->
				<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
    			<span class="navbar-toggler-icon"></span>
  				</button>
  				<!--END TOGGLE-->

  				<!--START NAVIGATION-->
  				<!--START NOW TIME-->
  				<div class="collapse navbar-collapse justify-content-end" id="Navber">
  					<ul class="navbar-nav">
				    	<li class="nav-item">
					        <span id="time" class="font-weight-bold text-white"></span>
					    </li>
					</ul>
				</div>
				<!--END NOW TIME-->

				<!--START LOGIN-->
  				<div class="collapse navbar-collapse justify-content-end" id="Navber">
  					{% if request.user.is_authenticated %}
  					<ul class="navbar-nav">
				      	<li class="nav-item text-white mr-3">
				        	
				      	</li>
				    </ul>
  					<ul class="navbar-nav">
				      	<li class="nav-item">
				        	<a class="nav-link" href="{% url 'image_app:logout' %}" onclick='return confirm("ログアウトしますか？");'>ログアウト</a>
				      	</li>
				    </ul>
				    {% else %}
				    <ul class="navbar-nav">
				      	<li class="nav-item">
				        	<a class="nav-link" href="{% url 'image_app:login' %}">ログイン</a>
				      	</li>
				    </ul>
  					<ul class="navbar-nav">
				      	<li class="nav-item">
				        	<a class="nav-link" href="{% url 'image_app:signup' %}">ユーザー登録</a>
				      	</li>
				    </ul>
				    {% endif %}
				</div>
				<!--END LOGNIN-->
				<!--END NAVIGATION-->	

			</nav>
			<!-- END NAVBAR -->

			<!--START MAIN-->
			<div class="col-lg-4 col-md-4 col-sm-4 mx-auto">
	        {% for message in messages %}
	            <p class="message-success">{{ message }}</p>
	        {% endfor %}
			</div>
			{% block content %}{% endblock %}
			<!--END MAIN-->
		</main>
		
		{# --- START JS --- #}
		<!--datatables.js-->
		<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/plug-ins/1.10.19/i18n/Japanese.json"></script>
	    <!-- JQUERY -->
	    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		{# --- END JS --- #}

	</body>

</html>